SOS-RS/frontend

src/lib/utils.ts, src/pages/Home/Home.tsx, src/pages/Shelter/components/ShelterCategoryItems/ShelterCategoryItems.tsx
Alteração na nomenclatura dos itens e aumento na quantidade de itens exibidos na página do abrigo.
=> change text and increase  items displayed

src/components/ShelterListItem/ShelterListItem.tsx, src/components/VerifiedBadge/VerifiedBadge.tsx, src/components/ui/with-tooltip.tsx, src/pages/Shelter/Shelter.tsx, tailwind.config.js
- Mudança de cor de vermelho pra azul
- Mudança de posição do início para o final do nome do abrigo
- Adicionado a funcionalidade de tooltip ao passar com o mouse ou clicar em cima do ícone de verificado
- Criado um componente `WithTooltip` para encapsular componentes dentro de tooltips de maneira reutilizável
- Criado um componente `VerifiedBadge` com o ícone de verificado e com a estilização específica de cor azul
=> feat: change verified badge color, position and added tooltip

README.md, src/lib/utils.ts, src/pages/CreateSupply/CreateSupply.tsx, src/pages/EditShelterSupply/EditShelterSupply.tsx, src/pages/EditShelterSupply/components/SupplyRow/SupplyRow.tsx, src/pages/Shelter/Shelter.tsx, src/pages/Shelter/components/ShelterCategoryItems/ShelterCategoryItems.tsx, src/service/supply/types.ts
**Importante mergear esse antes de qualquer outro**
PR para corrigir a branch `develop` e manter ela a frente da `master`.
Alguns PRs foram abertos e mergeados apontando diretamente para `master`.
A partir do merge desse PR aqui, todos os novos PRs devem apontar para `develop`.
=> Rebase Develop onto Master

src/components/ShelterListItem/ShelterListItem.tsx, src/hooks/useShelters/types.ts, src/lib/utils.ts, src/pages/Shelter/Shelter.tsx
⚠ THIS PR SHOULD BE MERGED TOGETHER WITH: https://github.com/SOS-RS/backend/pull/17
=> feat: added dedicated volunteers section to home and shelter pages

src/pages/Home/Home.tsx
- Esse PR irá:
-  [🐛 Fix reload button](https://github.com/SOS-RS/frontend/commit/f98c564612e6cc4e1aa8dd478c56c1de2c79794f)
- Conserta o erro do botão de reload. Basicamente, a aplicação
=> bug: Fix reload button

src/components/ShelterListItem/ShelterListItem.tsx
Esse erro impede o build ocorrer sem problemas.
=> fix no unused vars lint error

README.md
Olá ! apenas uma pequena correção da porta que o vite utiliza para desenvolvimento :)
=> fix: app port on README

src/pages/Home/components/ShelterListItem/ShelterListItem.tsx
Correção no typo de volunário -> voluntário
=> Shelter Titlle Volunteer Fix

README.md
Olá, pessoal! Pequena contribuição adicionando um link pra acessar a aplicação em produção com maior facilidade, e adicionando algumas das tecnologias utilizadas.
=> docs: add live link and tech stack to readme

src/components/CardAboutShelter/components/InfoRow/InfoRow.tsx, src/pages/Home/Home.tsx, src/pages/Home/components/ShelterListItem/ShelterListItem.tsx, src/pages/Home/components/ShelterListView/ShelterListView.tsx
Esse PR remove a lógica de navegação para favorecer o uso de links html ao invés da navegação imperativa via javascript.
Dessa maneira fica mais claro que todo o card é clicável, além de melhorar a acessibilidade e possibilidade de abrir a página em nova aba.
Foi também adicionado `hover:bg-accent` no card para melhorar a experiência.
=> Substitui onClick e useNavigate por <Link> para melhorar acessibilidade

src/components/LoadingSkeleton/LoadingSkeleton.tsx, src/components/LoadingSkeleton/index.ts, src/pages/Home/components/ShelterListView/ShelterListView.tsx
[Gravação de tela de 13-05-2024 18:25:11.webm](https://github.com/SOS-RS/frontend/assets/62677231/0dcc04c5-b03e-40ee-928c-b7fb9d38b2d6)
=> Add new feature and creating LoadingSkeleton

index.html
In this PR we fixed some SEO problems:
- Add favicon metatag to index.html, show SOS-RS icon in Search Engines.
- Add canonical metatag to index.html.
=> fix/add: add favicon and canonical metatag

src/hooks/useShelters/useShelters.tsx
https://github.com/SOS-RS/frontend/pull/137
=> Release 0.0.2

src/pages/AboutUs/AboutUs.tsx, src/pages/AboutUs/frontItems.tsx, src/pages/Home/components/Filter/types.ts
replaced all emoji occurences with lucide icons to avoid browser incompatibility #211
=> fix/ add lucide icons to replace emojis so it works across all browsers

src/pages/AboutUs/AboutUs.tsx, src/pages/AboutUs/types.ts
Contém as seguintes atualizações:
1. **Adição de Novos Contribuidores**:
- Adicionei menções a novos contribuidores na página "Sobre Nós".
2. **Refatoração da Renderização dos Contribuidores**:
- Refatorei o código que estava hard coded para utilizar um `.map` para renderizar a lista de contribuidores dinamicamente.
- Esta alteração torna o código mais limpo, modular e fácil de manter, além de facilitar futuras atualizações na lista de contribuidores.
3. **Atualização de Dados**:
- Atualizei os dados referentes à quantidade de abrigos, pessoas ajudadas, estrelas e forks no GitHub.
- Estes números agora refletem com precisão o impacto atual do nosso projeto e seu reconhecimento na comunidade open source.
=> feat: added more contributors to about me page

src/components/Header/Header.tsx
Fixado tamanho do botão para corrigir erro no Header
=> fix: :bug: Ajuste do tamanho do botao reload Issue 221

src/pages/Home/Home.tsx, src/pages/Home/components/Filter/Filter.tsx, src/pages/Home/components/Filter/types.ts
- changed name of array of priority to priorities;
- priority field changed from string to array
- removed unused import in home.tsx
=> fix: priorities

src/pages/Home/components/ShelterListView/ShelterListView.tsx
=> feat: Correção do título com/sem filtros #247

src/components/DonationCart/components/DonationSuccess/DonationSuccess.tsx, src/hooks/useDonations/index.ts, src/hooks/useDonations/types.ts, src/hooks/useDonations/useDonations.tsx, src/pages/DonationsHistory/DonationsHistory.tsx, src/pages/DonationsHistory/components/ConfirmationDialog.tsx, src/pages/DonationsHistory/components/Donation.tsx, src/pages/DonationsHistory/components/DonationsPerDay.tsx, src/pages/DonationsHistory/index.ts, src/pages/DonationsHistory/types.ts, src/pages/index.ts, src/routes/Routes.tsx, src/service/donationOrder/donationOrder.service.ts
- Adiciona nova rota '/abrigo/:shelterId/doacoes' para display de doações dos abrigos;
- Cria novo folder `DonationsHistory`;
- Cria Page `DonationsHistory` e components acessórios;
- Cria folder `useDonations`;
- Falta fazer a autenticação para que apenas o doador possa Confirmar ou Cancelar a doação. Essa funcionalidade necessita de uma tabela de join users_shelters no backend.
-  Após essa implementação, será refatorado para fazer a verificação. O PR foi feito para já liberar para QA.
Closes #327
=> Closes #327: Cria tela "List Donations" 

package-lock.json, package.json, src/hooks/useDonations/types.ts, src/pages/DonationsHistory/components/DonationHistoryListItem/DonationHistoryListItem.tsx, src/pages/DonationsHistory/components/DonationHistoryListItem/types.ts
Adicionado o comportamento de abrir tela de impressão ao clicar no ícone de imprimir em uma doação.
=> feat: added handle print on donation item
